pref("extensions.grabthemall.filetype", 1);
pref("extensions.grabthemall.completepage", 1);
pref("extensions.grabthemall.timeout", 10);
pref("extensions.grabthemall.timeToWait", 1);
pref("extensions.grabthemall.capture.width", 1024);
pref("extensions.grabthemall.capture.height", 768);
pref("extensions.grabthemall.capture.fileName", 0);
pref("extensions.grabthemall.debug", 0);
pref("extensions.grabthemall.reportfile.save", true);
